### ISSUE TITLE
CodedBy fails with optional dates decoding

### ISSUE THREAD

**Issue by murad1981** [SwiftyLab/MetaCodable#25]
I have the following `@Codable` model and its `HelperCoder` struct:

```
@Codable
struct TestModel {
    
    @CodedBy(DateCoder())
    var startDate: Date?
}

struct DateCoder: HelperCoder {
    func decode(from decoder: Decoder) throws -> Date? {
        var container = try decoder.unkeyedContainer()
        let dateStr = try container.decode(String.self)
        let df = ISO8601DateFormatter()
        let date = df.date(from: dateStr)
        return date
    }
}
```
the input JSON is 
```
{
"startDate": "2023-09-20T00:00:00Z"
}
```

I get this compiler error:

`Cannot assign value of type 'Date??' to type 'Date?'`

the expansion screenshot is as follows:

<img width="916" alt="Screenshot 2023-10-04 at 3 14 54 PM" src="https://github.com/SwiftyLab/MetaCodable/assets/1199045/f5dbdda8-270c-4447-bbd7-7a51ed9c7326">

**Comment by soumyamahunt** [comment]
> I have the following `@Codable` model and its `HelperCoder` struct:
> 
> ```
> @Codable
> struct TestModel {
>     
>     @CodedBy(DateCoder())
>     var startDate: Date?
> }
> 
> struct DateCoder: HelperCoder {
>     func decode(from decoder: Decoder) throws -> Date? {
>         var container = try decoder.unkeyedContainer()
>         let dateStr = try container.decode(String.self)
>         let df = ISO8601DateFormatter()
>         let date = df.date(from: dateStr)
>         return date
>     }
> }
> ```

Can you try with returning `Date` type instead of `Date?` in `DateCoder` implementation? That should fix your issue:
```
 struct DateCoder: HelperCoder {
     func decode(from decoder: Decoder) throws -> Date {
         var container = try decoder.unkeyedContainer()
         let dateStr = try container.decode(String.self)
         let df = ISO8601DateFormatter()
         let date = df.date(from: dateStr)
         return date
     }
 }
```

**Comment by murad1981** [comment]
That solves the syntax error but doesn't solve the problem, there should be a way to decode optional Dates, there are lots of use cases where we need something like: `var someDate: Date?` .

**Comment by soumyamahunt** [comment]
> That solves the syntax error but doesn't solve the problem, there should be a way to decode optional Dates by returning optional Date from the `HelperCoder`.

This use-case can be handled with current implementation as well, [`HelperCoder`](https://swiftylab.github.io/MetaCodable/documentation/metacodable/helpercoder) has optional requirement [`decodeIfPresent(from:)`](https://swiftylab.github.io/MetaCodable/documentation/metacodable/helpercoder/decodeifpresent(from:)-826qw/), which you can implement in your `DateCoder`, to indicate what happens when you want to decode optional `Date`.

The default implementation of [`decodeIfPresent(from:)`](https://swiftylab.github.io/MetaCodable/documentation/metacodable/helpercoder/decodeifpresent(from:)-826qw/) just returns result from [`decode(from:)`](https://swiftylab.github.io/MetaCodable/documentation/metacodable/helpercoder/decode(from:)) and returns `nil` if this method throws error.

**Comment by soumyamahunt** [comment]
> If I implement `decodeIfPresent(from: )` instead of `decode(from:)` in the `HelperCoder`,  the compiler auto completes the function signature with the return type of `Date??` which should be `Date?`.

Can you share the implementation snippet you are trying? I will be able to suggest changes that will make your use-case work.

**Comment by murad1981** [comment]
Sample app is attached, please don't return non-optional `Date` from the `decode(from:)` method as a workaround solution to the problem, because I need to store nil `Date?` in the model for some cases.
[TestCodableMacro.zip](https://github.com/SwiftyLab/MetaCodable/files/12804152/TestCodableMacro.zip)

**Comment by murad1981** [comment]
As I mentioned above I can't use `func decodeIfPresent(from decoder: Decoder) throws -> Date?` alone to satisfy my requirement which is storing nil date in my model, as the compiler throws this error: 

`Type 'DateCoder' does not conform to protocol 'HelperCoder'`

The compiler suggests to use: `func decodeIfPresent(from decoder: Decoder) throws -> Date??` 
notice the double question mark in the return type.

Using `func decode(from decoder: Decoder) throws -> Date` is useless for the current case as it should return a `Date` not `Date?`

**Comment by murad1981** [comment]
Thank you @soumyamahunt for the last pattern you provided which really solves the issue, but the only take away in this pattern is that I must provide the implementation of `decode(from:)` to avoid the compiler error: `Type 'DateCoder' does not conform to protocol 'HelperCoder'`, so I just implemented it like this to return a dummy date:

```
func decode(from decoder: Decoder) -> Date {
         Date()
    }
```

if you could fix this to only require `func decodeIfPresent(from:)` when the model value is optional that would be cool

**Comment by soumyamahunt** [comment]
> if you could fix this to only require `func decodeIfPresent(from:)` when the model value is optional that would be cool

The use of `HelperCodable` is to provide custom decoder/encoder that will decode/encode a type and it's optional variant. This is the same in principle with the standard library where `decode` is used to decode a basic type (i.e. `Int`) `decodeIfPresent` to decode optional of that type.

You should implement `decode(from:)` to decode the actual `Date` type and reuse that implementation in `decodeIfPresent(from:)` and provide custom logic to handle failure (i.e. returning `nil`).

Anyway, closing this since there is no issue here.
