### ISSUE TITLE
Only 21 of 75 Tests succeed when running them on main.

### ISSUE THREAD

**Issue by Midbin** [SwiftyLab/MetaCodable#28]
When trying to work on some of the issues I filed earlier today, I discovered that when running the tests on main (simply opening the Package.swift in XCode an pressing Command + U) about 75% of the Tests fail.

The failures seem to indicate that `@Codable` is not expanded:

An example failure:
```
CodableTests.swift:75: failed - Actual output (+) differed from expected output (-):
 struct SomeCodable: Encodable {
     let value: String
 
     func encode(to encoder: Encoder) throws {
     }
 }
–
–extension SomeCodable: Decodable {
–    init(from decoder: Decoder) throws {
–        let container = try decoder.container(keyedBy: CodingKeys.self)
–        self.value = try container.decode(String.self, forKey: CodingKeys.value)
–    }
–}
–
–extension SomeCodable {
–    enum CodingKeys: String, CodingKey {
–        case value = "value"
–    }
–}

Actual expanded source:

struct SomeCodable: Encodable {
    let value: String

    func encode(to encoder: Encoder) throws {
    }
}
```

Is this an error on my end?

**Comment by soumyamahunt** [comment]
This is because [testing of extension macros are not supported by swift-syntax](https://github.com/apple/swift-syntax/issues/2031).

The workaround I use currently to test is to comment these lines and run tests to check:

https://github.com/SwiftyLab/MetaCodable/blob/main/Sources/CodableMacroPlugin/Registration/Registrar.swift#L121-L127

https://github.com/SwiftyLab/MetaCodable/blob/main/Sources/CodableMacroPlugin/Registration/Registrar.swift#L129-L131

https://github.com/SwiftyLab/MetaCodable/blob/main/Sources/CodableMacroPlugin/Registration/Registrar.swift#L133-L139

https://github.com/SwiftyLab/MetaCodable/blob/main/Sources/CodableMacroPlugin/Registration/Registrar.swift#L141-L143

With these lines commented most of the test cases will pass but some cases asserting extension macro behaviour will fail.

I am waiting for a fix from swift-syntax so that I can and unit tests part of CI. Until then this work around is all I have.

**Comment by soumyamahunt** [comment]
@Midbin I have added fix in my forked version of swift-syntax which is now used by this library, [hopefully the fix is accepted by upstream](https://github.com/apple/swift-syntax/pull/2327).

The fix works well with VSCode without any additional steps.
For XCode, you might need to comment out line `49` and `63` in `Package.swift`:
https://github.com/SwiftyLab/MetaCodable/blob/5344f133a6458fa20458427e8f3fed252907fda4/Package.swift#L49
https://github.com/SwiftyLab/MetaCodable/blob/5344f133a6458fa20458427e8f3fed252907fda4/Package.swift#L63
