### ISSUE TITLE
Note of appreciation :) + Some questions

### ISSUE THREAD

**Issue by Ariandr** [SwiftyLab/MetaCodable#41]
Hello @soumyamahunt 
Thank you for your work, sincerely!
When I saw this repo, I was pleasantly surprised🙂

Finally I feel like I have something to switch to instead of using SwiftyJSON, because default Codable was never good for dynamic responses with absent values and dynamic structure.

Question:
Now I wonder if it's possible to add something like this, cause I didn't work with Macros and don't really know what's possible.

```
@CodedAt("title", or: "title_name")
let title: String
```

If the title can come in JSON inside "title" key, and if not present, look for `or` "title_name" key.

Keep up the good work👋👋👋

**Comment by soumyamahunt** [comment]
> Hello @soumyamahunt Thank you for your work, sincerely! When I saw this repo, I was pleasantly surprised🙂
> 
> Finally I feel like I have something to switch to instead of using SwiftyJSON, because default Codable was never good for dynamic responses with absent values and dynamic structure.

Thanks @Ariandr. The goal of the library is to address all the possible needs with decoding/encoding with a type safe manner complementing `Codable` standard instead of going against it.

> 
> Question: Now I wonder if it's possible to add something like this, cause I didn't work with Macros and don't really know what's possible.
> 
> ```
> @CodedAt("title", or: "title_name")
> let title: String
> ```
> 
> If the title can come in JSON inside "title" key, and if not present, look for `or` "title_name" key.

This can be addressed with current implementation of library as well. Such case is a good example of writing specific [`HelperCoder`](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/helpercoder) for. Your `title` property could look like this:

```swift
@CodedAt
@CodedBy(your_custom_helper_coder)
let title: String
```

And in your custom [`HelperCoder`](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/helpercoder)'s [`decode(from:)`](https://swiftpackageindex.com/swiftylab/metacodable/main/documentation/metacodable/helpercoder/decode(from:)) method you can implement your custom decoding logic. 

I want library to handle such niche cases as well with the launch of [`HelperCoders`](https://swiftpackageindex.com/SwiftyLab/MetaCodable/main/documentation/helpercoders) module that contains common helper functionality. PRs are welcome if you think this use-case will help others as well.

> Keep up the good work👋👋👋

Thank you for you support.

**Comment by Ariandr** [comment]
Thanks for your reply!
When I have time, I will try to check everything in more detail👍

**Comment by keepyounger** [comment]
邮件已收到，感谢您的来信!
我会尽快联系你的。

**Comment by soumyamahunt** [comment]
@Ariandr new macro `@CodedAs` has been [released](https://github.com/SwiftyLab/MetaCodable/releases/tag/v1.2.0) that allows declaring multiple key aliases:
```swift
@CodedAs("title_name")
let title: String
```

**Comment by Ariandr** [comment]
Hi @soumyamahunt 
Awesome, you rock! What a great work on your side. Thank you!

Now I can use:
```
@CodedAs("title_name", "title")
let title: String
```

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt 
> Awesome, you rock! What a great work on your side. Thank you!
> 
> Now I can use:
> ```
> @CodedAs("title_name", "title")
> let title: String
> ```
> 
> Or I don't event need to specify the "title", it will take the property name? :)

Thanks @Ariandr!

You don't have to specify "title" in case of fields,  by default it will be taken from the field name.

**Comment by Ariandr** [comment]
Thank you, clear!
